server:
  shutdown: graceful
  address: 0.0.0.0
  port: 8080

spring:
  config:
    import: "classpath:/yaml/"

  lifecycle:
    timeout-per-shutdown-phase: 10s
  profiles:
    include: secret

  devtools:
    livereload:
      enabled: true

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  data:
    redis:
      host: 43.200.193.73
      port: 6379

cloud:
  aws:
    stack:
      auto: false
    region:
      static-region: ap-northeast-2